uv run python trainers/train_gpt_v4.py \
    --train-manifest seasalt-processed/train_gpt.jsonl \
    --val-manifest seasalt-processed/valid_gpt.jsonl \
    --tokenizer checkpoints/bpe.model \
    --config checkpoints/config.yaml \
    --base-checkpoint checkpoints/gpt.pth \
    --output-dir v4_trained_ckpts_paired \
    --batch-size 2 \
    --grad-accumulation 8 \
    --epochs 200 \
    --learning-rate 4e-4 \
    --weight-decay 0.01 \
    --warmup-steps 100 \
    --log-interval 1 \
    --val-interval 2000 \
    --grad-clip 1.0 \
    --text-loss-weight 0.2 \
    --mel-loss-weight 0.8 \
    --amp \
    --resume auto
